# Generated by Django 4.2 on 2024-04-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_place_lat_place_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
