# Generated by Django 4.2 on 2024-04-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_placeimage_order'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='placeimage',
            index=models.Index(fields=['order'], name='places_plac_order_66e296_idx'),
        ),
    ]
