# Generated by Django 4.2 on 2024-04-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_placeimage_places_plac_order_66e296_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
    ]
