# Generated by Django 4.2 on 2024-05-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_remove_placeimage_places_plac_order_66e296_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название'),
        ),
    ]
